spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
message: Hello Dev!
---
spring:
  config:
    activate:
      on-profile: prod
message: Hello Prod!

---

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false