spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
message: Hello Dev!
---
spring:
  config:
    activate:
      on-profile: prod
message: Hello Prod!

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop